### PR TITLE
Add support for global access to the widget by passing ref

### PR DESCRIPTION
**Pull request by reznord**
Right now there is no way to access the widget from the global scope. For eg: if I want to access the widget on a global scope (`window.widget.foo()`) it is not possible till now because it wasn't possible to add a reference on the widget level.

This PR adds support for adding ref to the component itself.

### CODE REVIEW

**Comment by bumi** [comment]
I like that this makes the widget accessible to programatically control it. 

would it be possible to somehow return the object by the `.render`  function? This would allow to have multiple widgets on the same page and make all of those accessible. 
```js
let myWidget = _habitat.render({...}); 
```

**Comment by bumi** [comment]
do you think this can make it in master? would be super helpful. //cc @zouhir

**Comment by bumi** [comment]
@zouhir friendly ping. do you think this could make it in a release?

**Comment by zouhir** [comment]
hi @bumi @reznord -- happy to give either of you, or both, full GitHub & npm permissions to this project so you can merge improvements, and release to your liking. please let me know if interested. I would appreciate your help!

**Comment by bumi** [comment]
hey @zouhir that's nice. Though I think I am not a very good maintainer for the library as I know too little about preact and the details of this library. 
I think @reznord is the right person to support!! <3

**Pull request closed without merging**
