### PR TITLE
Allow application/json script type

### PR DESCRIPTION
**Pull request by ascorbic**
This PR adds support for application/json type for props, which is more standards-compliant and matches other uses of embedded JSON such as AMP.

### CODE REVIEW

**Comment by ascorbic** [comment]
Prettier now supports `<script type="application/json">`: https://github.com/prettier/prettier/pull/6293 so this would be extra useful.

**Comment by lydell** [comment]
Did you accidentally commit `.vscode/` and `dist/`?

**Comment by ascorbic** [comment]
Ah, damn you're right. I did the pr from the wrong branch. I have one with dist committed so I can do a yarn install from GitHub. I'm on holiday all week so can't update the pr.

**Comment by ascorbic** [comment]
I've .gitignored them, but it looks like `dist` was actually already committed. This PR will now remove the dist directory too.

**Comment by ascorbic** [comment]
OK, I've actually reverted the removal of dist, because it looks like quite a few people may have been installing it directly from git, as the latest version hasn't been push to npm.

**Pull request merged**
